// AUTO-GENERATED by scripts/gen-promo-timings.mjs — do not edit by hand.
// Scene durations (seconds) + phrase marks (frames, scene-relative) locked to
// the narration take (75.47s total).
export const FPS = 30;
export const NARRATION_SECONDS = 75.47;
export const SCENES = [
  {
    "k": "hook",
    "s": 11.02,
    "marks": {
      "sub": 122,
      "keeps": 233
    }
  },
  {
    "k": "sweep",
    "s": 10.12,
    "marks": {
      "f0": 89,
      "f1": 134,
      "f2": 182,
      "f3": 209,
      "f4": 250
    }
  },
  {
    "k": "p1",
    "s": 9.93,
    "marks": {
      "chip": 242
    }
  },
  {
    "k": "p2",
    "s": 11.18,
    "marks": {
      "chip": 220
    }
  },
  {
    "k": "p3",
    "s": 7.62,
    "marks": {
      "chip": 102
    }
  },
  {
    "k": "adds",
    "s": 8.63,
    "marks": {
      "chip": 150,
      "show": 205
    }
  },
  {
    "k": "outcome",
    "s": 8.2,
    "marks": {
      "l0": 53,
      "l1": 134,
      "l2": 195
    }
  },
  {
    "k": "cta",
    "s": 8.78,
    "marks": {
      "btn": 167,
      "url": 235
    }
  }
] as const;
export type SceneKey = typeof SCENES[number]['k'];
